### ISSUE TITLE
컬렉션 뷰 구성

### ISSUE THREAD

**Issue by angry-dev** [APPSCHOOL1-REPO/finalproject-goodvibe#47]
# Todo
- [x] User 컬렉션 하위 LikedStore 컬렉션 추가
- [x] 찜한 가게 목록을 리스트뷰로 표현
- [x] store에 담긴 가게 shuffle해서 콜렉션 뷰에 구현

# Nightmare
- [ ] 이미지 불러오기
- [x] 찜 해제시 뷰 갱신 -> 우선 ContextMenu로 대체
